package com.carddemo.transaction;

import com.carddemo.account.Account;
import com.carddemo.card.Card;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * JPA Entity representing the Transaction table in PostgreSQL database.
 * 
 * This entity maps the COBOL TRAN-RECORD structure from CVTRA05Y.cpy copybook
 * to PostgreSQL table with comprehensive field validation, optimistic locking,
 * and entity relationships while preserving exact data precision and business 
 * rules from the original COBOL record structures.
 * 
 * Original COBOL Structure (CVTRA05Y.cpy):
 * 01  TRAN-RECORD.
 *     05  TRAN-ID                                 PIC X(16).
 *     05  TRAN-TYPE-CD                            PIC X(02).
 *     05  TRAN-CAT-CD                             PIC 9(04).
 *     05  TRAN-SOURCE                             PIC X(10).
 *     05  TRAN-DESC                               PIC X(100).
 *     05  TRAN-AMT                                PIC S9(09)V99.
 *     05  TRAN-MERCHANT-ID                        PIC 9(09).
 *     05  TRAN-MERCHANT-NAME                      PIC X(50).
 *     05  TRAN-MERCHANT-CITY                      PIC X(50).
 *     05  TRAN-MERCHANT-ZIP                       PIC X(10).
 *     05  TRAN-CARD-NUM                           PIC X(16).
 *     05  TRAN-ORIG-TS                            PIC X(26).
 *     05  TRAN-PROC-TS                            PIC X(26).
 *     05  FILLER                                  PIC X(20).
 * 
 * PostgreSQL Table Mapping:
 * - Primary Key: transaction_id (VARCHAR(16))
 * - Foreign Keys: card_number references cards(card_number), account_id references accounts(account_id)
 * - Monetary Fields: transaction_amount (NUMERIC(15,2)) for exact precision
 * - Optimistic Locking: row_version (INTEGER)
 * - Audit Fields: created_at, updated_at (TIMESTAMP)
 * 
 * Performance Considerations:
 * - Composite indexes on (card_number, transaction_timestamp) for transaction history queries
 * - Index on account_id for balance calculation and reporting operations
 * - Index on merchant_id for merchant transaction analysis
 * - Index on transaction_type_cd for categorization and reporting
 * 
 * Business Rules:
 * - Transaction amounts must maintain COBOL S9(09)V99 precision using BigDecimal
 * - Transaction IDs must be exactly 16 characters for compatibility
 * - Card numbers must reference valid cards in cards table
 * - All timestamp fields automatically managed by JPA for audit compliance
 * - Optimistic locking prevents concurrent transaction modifications
 * 
 * @author Blitzy Agent - Generated from COBOL CVTRA05Y.cpy
 * @version 1.0
 * @since 2024-01-01
 */
@Entity
@Table(name = "transactions", indexes = {
    @Index(name = "idx_transactions_card_number", columnList = "card_number"),
    @Index(name = "idx_transactions_account_id", columnList = "account_id"),
    @Index(name = "idx_transactions_type_cd", columnList = "transaction_type_cd"),
    @Index(name = "idx_transactions_category_cd", columnList = "transaction_category_cd"),
    @Index(name = "idx_transactions_merchant_id", columnList = "merchant_id"),
    @Index(name = "idx_transactions_orig_ts", columnList = "transaction_orig_ts"),
    @Index(name = "idx_transactions_card_ts", columnList = "card_number, transaction_orig_ts"),
    @Index(name = "idx_transactions_account_ts", columnList = "account_id, transaction_orig_ts")
})
public class Transaction implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Primary key: 16-character transaction identifier from COBOL TRAN-ID PIC X(16)
     * 
     * Business Rules:
     * - Must be exactly 16 characters
     * - Unique across all transactions
     * - Maps to PostgreSQL VARCHAR(16)
     * - Generated by application for new transactions
     */
    @Id
    @Column(name = "transaction_id", length = 16, nullable = false)
    @NotBlank(message = "Transaction ID is required")
    @Size(min = 16, max = 16, message = "Transaction ID must be exactly 16 characters")
    @Pattern(regexp = "^[A-Za-z0-9]{16}$", message = "Transaction ID must contain only alphanumeric characters")
    private String transactionId;

    /**
     * Transaction type code from COBOL TRAN-TYPE-CD PIC X(02)
     * 
     * Business Rules:
     * - Must be exactly 2 characters
     * - References transaction_types lookup table
     * - Common values: 01=Purchase, 02=Cash Advance, 03=Payment, 04=Fee, 05=Interest
     * - Required for transaction categorization and processing rules
     */
    @Column(name = "transaction_type_cd", length = 2, nullable = false)
    @NotBlank(message = "Transaction type code is required")
    @Size(min = 2, max = 2, message = "Transaction type code must be exactly 2 characters")
    @Pattern(regexp = "^[0-9]{2}$", message = "Transaction type code must be exactly 2 digits")
    private String transactionTypeCd;

    /**
     * Transaction category code from COBOL TRAN-CAT-CD PIC 9(04)
     * 
     * Business Rules:
     * - Must be exactly 4 digits
     * - References transaction_categories lookup table
     * - Used for merchant category classification (MCC codes)
     * - Required for transaction processing and reporting
     */
    @Column(name = "transaction_category_cd", length = 4, nullable = false)
    @NotBlank(message = "Transaction category code is required")
    @Size(min = 4, max = 4, message = "Transaction category code must be exactly 4 characters")
    @Pattern(regexp = "^[0-9]{4}$", message = "Transaction category code must be exactly 4 digits")
    private String transactionCategoryCd;

    /**
     * Transaction source from COBOL TRAN-SOURCE PIC X(10)
     * 
     * Business Rules:
     * - Maximum 10 characters
     * - Identifies transaction origin (ATM, POS, ONLINE, PHONE, etc.)
     * - Used for transaction processing and fraud detection
     * - Required field for audit and compliance
     */
    @Column(name = "transaction_source", length = 10, nullable = false)
    @NotBlank(message = "Transaction source is required")
    @Size(max = 10, message = "Transaction source cannot exceed 10 characters")
    @Pattern(regexp = "^[A-Z0-9\\s]{1,10}$", message = "Transaction source must contain only uppercase letters, digits, and spaces")
    private String transactionSource;

    /**
     * Transaction description from COBOL TRAN-DESC PIC X(100)
     * 
     * Business Rules:
     * - Maximum 100 characters
     * - Free-form description of transaction
     * - Used for customer statement display
     * - May contain merchant name or transaction details
     */
    @Column(name = "transaction_desc", length = 100, nullable = false)
    @NotBlank(message = "Transaction description is required")
    @Size(max = 100, message = "Transaction description cannot exceed 100 characters")
    private String transactionDesc;

    /**
     * Transaction amount from COBOL TRAN-AMT PIC S9(09)V99
     * 
     * Business Rules:
     * - Signed decimal with 2-decimal precision for monetary calculations
     * - Positive for debits (purchases, fees), negative for credits (payments, refunds)
     * - Must maintain exact COBOL precision using BigDecimal
     * - Required for balance calculations and financial reporting
     * - Maximum 9 integer digits, 2 decimal places (up to $999,999,999.99)
     */
    @Column(name = "transaction_amount", precision = 15, scale = 2, nullable = false)
    @NotNull(message = "Transaction amount cannot be null")
    @Digits(integer = 13, fraction = 2, message = "Transaction amount must have at most 13 integer digits and 2 decimal places")
    private BigDecimal transactionAmount;

    /**
     * Merchant identifier from COBOL TRAN-MERCHANT-ID PIC 9(09)
     * 
     * Business Rules:
     * - 9-digit numeric merchant identifier
     * - References merchant database for transaction processing
     * - Required for merchant settlement and reporting
     * - Zero indicates internal transaction (fees, interest, etc.)
     */
    @Column(name = "merchant_id", length = 9, nullable = false)
    @NotBlank(message = "Merchant ID is required")
    @Pattern(regexp = "^[0-9]{9}$", message = "Merchant ID must be exactly 9 digits")
    private String merchantId;

    /**
     * Merchant name from COBOL TRAN-MERCHANT-NAME PIC X(50)
     * 
     * Business Rules:
     * - Maximum 50 characters
     * - Display name for merchant on customer statements
     * - Used for transaction identification and customer service
     * - May be different from legal merchant name
     */
    @Column(name = "merchant_name", length = 50, nullable = false)
    @NotBlank(message = "Merchant name is required")
    @Size(max = 50, message = "Merchant name cannot exceed 50 characters")
    private String merchantName;

    /**
     * Merchant city from COBOL TRAN-MERCHANT-CITY PIC X(50)
     * 
     * Business Rules:
     * - Maximum 50 characters
     * - City where transaction occurred
     * - Used for fraud detection and customer recognition
     * - Required for transaction location tracking
     */
    @Column(name = "merchant_city", length = 50, nullable = false)
    @NotBlank(message = "Merchant city is required")
    @Size(max = 50, message = "Merchant city cannot exceed 50 characters")
    private String merchantCity;

    /**
     * Merchant ZIP code from COBOL TRAN-MERCHANT-ZIP PIC X(10)
     * 
     * Business Rules:
     * - Maximum 10 characters (supports ZIP+4 format)
     * - Postal code where transaction occurred
     * - Used for fraud detection and geographic analysis
     * - Required for transaction location tracking
     */
    @Column(name = "merchant_zip", length = 10, nullable = false)
    @NotBlank(message = "Merchant ZIP code is required")
    @Size(max = 10, message = "Merchant ZIP code cannot exceed 10 characters")
    @Pattern(regexp = "^[0-9]{5}(-[0-9]{4})?$", message = "Merchant ZIP code must be in format 12345 or 12345-6789")
    private String merchantZip;

    /**
     * Card number from COBOL TRAN-CARD-NUM PIC X(16)
     * 
     * Business Rules:
     * - Must be exactly 16 digits
     * - References cards table for card validation
     * - Required for transaction authorization and processing
     * - Used for customer account identification
     */
    @Column(name = "card_number", length = 16, nullable = false)
    @NotBlank(message = "Card number is required")
    @Pattern(regexp = "^[0-9]{16}$", message = "Card number must be exactly 16 digits")
    private String cardNumber;

    /**
     * Account ID for transaction posting
     * 
     * Business Rules:
     * - Must be exactly 11 digits
     * - References accounts table for balance updates
     * - Required for transaction posting and account management
     * - Derived from card-account relationship
     */
    @Column(name = "account_id", length = 11, nullable = false)
    @NotBlank(message = "Account ID is required")
    @Pattern(regexp = "^[0-9]{11}$", message = "Account ID must be exactly 11 digits")
    private String accountId;

    /**
     * Original transaction timestamp from COBOL TRAN-ORIG-TS PIC X(26)
     * 
     * Business Rules:
     * - Timestamp when transaction originally occurred
     * - Used for transaction sequencing and fraud detection
     * - Required for transaction chronology and reporting
     * - Automatically set for new transactions
     */
    @Column(name = "transaction_orig_ts", nullable = false)
    @NotNull(message = "Original transaction timestamp is required")
    private LocalDateTime transactionOrigTs;

    /**
     * Processing timestamp from COBOL TRAN-PROC-TS PIC X(26)
     * 
     * Business Rules:
     * - Timestamp when transaction was processed by system
     * - Used for batch processing and settlement
     * - May differ from original timestamp for offline transactions
     * - Automatically set during transaction processing
     */
    @Column(name = "transaction_proc_ts", nullable = false)
    @NotNull(message = "Processing timestamp is required")
    private LocalDateTime transactionProcTs;

    /**
     * Optimistic locking version field for concurrent access control
     * 
     * Replaces CICS record-level sharing (RLS) with JPA optimistic locking.
     * Automatically managed by JPA framework for concurrent modification detection.
     */
    @Version
    @Column(name = "row_version", nullable = false)
    private Integer rowVersion = 0;

    /**
     * Audit field: Record creation timestamp
     * 
     * Automatically populated when entity is first persisted.
     * Provides audit trail for compliance and troubleshooting.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Audit field: Record last update timestamp
     * 
     * Automatically updated when entity is modified.
     * Provides audit trail for compliance and troubleshooting.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Bidirectional relationship with Card entity
     * 
     * Maps foreign key card_number to Card entity through JPA association.
     * Enables navigation from Transaction to Card for business operations.
     * Uses FetchType.LAZY for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "card_number", referencedColumnName = "card_number", 
                insertable = false, updatable = false,
                foreignKey = @ForeignKey(name = "fk_transactions_card"))
    private Card card;

    /**
     * Bidirectional relationship with Account entity
     * 
     * Maps foreign key account_id to Account entity through JPA association.
     * Enables navigation from Transaction to Account for balance operations.
     * Uses FetchType.LAZY for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "account_id", referencedColumnName = "account_id", 
                insertable = false, updatable = false,
                foreignKey = @ForeignKey(name = "fk_transactions_account"))
    private Account account;

    /**
     * Default constructor required by JPA specification
     */
    public Transaction() {
        // Default constructor for JPA
    }

    /**
     * Constructor for creating new Transaction entity with required fields
     * 
     * @param transactionId 16-character transaction identifier
     * @param transactionTypeCd 2-character transaction type code
     * @param transactionCategoryCd 4-digit transaction category code
     * @param transactionSource Transaction source (max 10 chars)
     * @param transactionDesc Transaction description (max 100 chars)
     * @param transactionAmount Transaction amount with 2-decimal precision
     * @param merchantId 9-digit merchant identifier
     * @param merchantName Merchant name (max 50 chars)
     * @param merchantCity Merchant city (max 50 chars)
     * @param merchantZip Merchant ZIP code (max 10 chars)
     * @param cardNumber 16-digit card number
     * @param accountId 11-digit account identifier
     */
    public Transaction(String transactionId, String transactionTypeCd, String transactionCategoryCd,
                      String transactionSource, String transactionDesc, BigDecimal transactionAmount,
                      String merchantId, String merchantName, String merchantCity, String merchantZip,
                      String cardNumber, String accountId) {
        this.transactionId = transactionId;
        this.transactionTypeCd = transactionTypeCd;
        this.transactionCategoryCd = transactionCategoryCd;
        this.transactionSource = transactionSource;
        this.transactionDesc = transactionDesc;
        this.transactionAmount = transactionAmount;
        this.merchantId = merchantId;
        this.merchantName = merchantName;
        this.merchantCity = merchantCity;
        this.merchantZip = merchantZip;
        this.cardNumber = cardNumber;
        this.accountId = accountId;
        this.transactionOrigTs = LocalDateTime.now();
        this.transactionProcTs = LocalDateTime.now();
    }

    /**
     * Constructor for creating Transaction with specific timestamps
     * 
     * @param transactionId 16-character transaction identifier
     * @param transactionTypeCd 2-character transaction type code
     * @param transactionCategoryCd 4-digit transaction category code
     * @param transactionSource Transaction source (max 10 chars)
     * @param transactionDesc Transaction description (max 100 chars)
     * @param transactionAmount Transaction amount with 2-decimal precision
     * @param merchantId 9-digit merchant identifier
     * @param merchantName Merchant name (max 50 chars)
     * @param merchantCity Merchant city (max 50 chars)
     * @param merchantZip Merchant ZIP code (max 10 chars)
     * @param cardNumber 16-digit card number
     * @param accountId 11-digit account identifier
     * @param transactionOrigTs Original transaction timestamp
     * @param transactionProcTs Processing timestamp
     */
    public Transaction(String transactionId, String transactionTypeCd, String transactionCategoryCd,
                      String transactionSource, String transactionDesc, BigDecimal transactionAmount,
                      String merchantId, String merchantName, String merchantCity, String merchantZip,
                      String cardNumber, String accountId, LocalDateTime transactionOrigTs, LocalDateTime transactionProcTs) {
        this(transactionId, transactionTypeCd, transactionCategoryCd, transactionSource, transactionDesc,
             transactionAmount, merchantId, merchantName, merchantCity, merchantZip, cardNumber, accountId);
        this.transactionOrigTs = transactionOrigTs;
        this.transactionProcTs = transactionProcTs;
    }

    // Getters and Setters with validation

    /**
     * Gets the transaction identifier
     * 
     * @return transaction ID as string
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the transaction identifier
     * 
     * @param transactionId 16-character transaction ID
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Gets the transaction type code
     * 
     * @return transaction type code as string
     */
    public String getTransactionTypeCd() {
        return transactionTypeCd;
    }

    /**
     * Sets the transaction type code
     * 
     * @param transactionTypeCd 2-character transaction type code
     */
    public void setTransactionTypeCd(String transactionTypeCd) {
        this.transactionTypeCd = transactionTypeCd;
    }

    /**
     * Gets the transaction category code
     * 
     * @return transaction category code as string
     */
    public String getTransactionCategoryCd() {
        return transactionCategoryCd;
    }

    /**
     * Sets the transaction category code
     * 
     * @param transactionCategoryCd 4-digit transaction category code
     */
    public void setTransactionCategoryCd(String transactionCategoryCd) {
        this.transactionCategoryCd = transactionCategoryCd;
    }

    /**
     * Gets the transaction source
     * 
     * @return transaction source as string
     */
    public String getTransactionSource() {
        return transactionSource;
    }

    /**
     * Sets the transaction source
     * 
     * @param transactionSource transaction source (max 10 chars)
     */
    public void setTransactionSource(String transactionSource) {
        this.transactionSource = transactionSource;
    }

    /**
     * Gets the transaction description
     * 
     * @return transaction description as string
     */
    public String getTransactionDesc() {
        return transactionDesc;
    }

    /**
     * Sets the transaction description
     * 
     * @param transactionDesc transaction description (max 100 chars)
     */
    public void setTransactionDesc(String transactionDesc) {
        this.transactionDesc = transactionDesc;
    }

    /**
     * Gets the transaction amount
     * 
     * @return transaction amount as BigDecimal
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the transaction amount
     * 
     * @param transactionAmount transaction amount with 2-decimal precision
     */
    public void setTransactionAmount(BigDecimal transactionAmount) {
        this.transactionAmount = transactionAmount;
    }

    /**
     * Gets the merchant identifier
     * 
     * @return merchant ID as string
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the merchant identifier
     * 
     * @param merchantId 9-digit merchant ID
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * Gets the merchant name
     * 
     * @return merchant name as string
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the merchant name
     * 
     * @param merchantName merchant name (max 50 chars)
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Gets the merchant city
     * 
     * @return merchant city as string
     */
    public String getMerchantCity() {
        return merchantCity;
    }

    /**
     * Sets the merchant city
     * 
     * @param merchantCity merchant city (max 50 chars)
     */
    public void setMerchantCity(String merchantCity) {
        this.merchantCity = merchantCity;
    }

    /**
     * Gets the merchant ZIP code
     * 
     * @return merchant ZIP code as string
     */
    public String getMerchantZip() {
        return merchantZip;
    }

    /**
     * Sets the merchant ZIP code
     * 
     * @param merchantZip merchant ZIP code (max 10 chars)
     */
    public void setMerchantZip(String merchantZip) {
        this.merchantZip = merchantZip;
    }

    /**
     * Gets the card number
     * 
     * @return card number as string
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the card number
     * 
     * @param cardNumber 16-digit card number
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * Gets the account identifier
     * 
     * @return account ID as string
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the account identifier
     * 
     * @param accountId 11-digit account ID
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * Gets the original transaction timestamp
     * 
     * @return original timestamp as LocalDateTime
     */
    public LocalDateTime getTransactionOrigTs() {
        return transactionOrigTs;
    }

    /**
     * Sets the original transaction timestamp
     * 
     * @param transactionOrigTs original transaction timestamp
     */
    public void setTransactionOrigTs(LocalDateTime transactionOrigTs) {
        this.transactionOrigTs = transactionOrigTs;
    }

    /**
     * Gets the processing timestamp
     * 
     * @return processing timestamp as LocalDateTime
     */
    public LocalDateTime getTransactionProcTs() {
        return transactionProcTs;
    }

    /**
     * Sets the processing timestamp
     * 
     * @param transactionProcTs processing timestamp
     */
    public void setTransactionProcTs(LocalDateTime transactionProcTs) {
        this.transactionProcTs = transactionProcTs;
    }

    /**
     * Gets the optimistic locking version
     * 
     * @return row version number
     */
    public Integer getRowVersion() {
        return rowVersion;
    }

    /**
     * Sets the optimistic locking version
     * 
     * Note: This should typically only be used by JPA framework
     * 
     * @param rowVersion version number
     */
    public void setRowVersion(Integer rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * Gets the record creation timestamp
     * 
     * @return creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Gets the record last update timestamp
     * 
     * @return last update timestamp
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Gets the associated Card entity
     * 
     * @return Card entity or null if not loaded
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the associated Card entity
     * 
     * @param card Card entity to associate
     */
    public void setCard(Card card) {
        this.card = card;
    }

    /**
     * Gets the associated Account entity
     * 
     * @return Account entity or null if not loaded
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Sets the associated Account entity
     * 
     * @param account Account entity to associate
     */
    public void setAccount(Account account) {
        this.account = account;
    }

    // Business Logic Helper Methods

    /**
     * Checks if the transaction is a debit (positive amount)
     * 
     * Replicates COBOL 88-level condition logic for amount validation
     * 
     * @return true if transaction amount is positive (debit)
     */
    public boolean isDebit() {
        return transactionAmount != null && transactionAmount.compareTo(BigDecimal.ZERO) > 0;
    }

    /**
     * Checks if the transaction is a credit (negative amount)
     * 
     * @return true if transaction amount is negative (credit)
     */
    public boolean isCredit() {
        return transactionAmount != null && transactionAmount.compareTo(BigDecimal.ZERO) < 0;
    }

    /**
     * Checks if the transaction is a purchase (type 01)
     * 
     * @return true if transaction type is '01' (Purchase)
     */
    public boolean isPurchase() {
        return "01".equals(transactionTypeCd);
    }

    /**
     * Checks if the transaction is a cash advance (type 02)
     * 
     * @return true if transaction type is '02' (Cash Advance)
     */
    public boolean isCashAdvance() {
        return "02".equals(transactionTypeCd);
    }

    /**
     * Checks if the transaction is a payment (type 03)
     * 
     * @return true if transaction type is '03' (Payment)
     */
    public boolean isPayment() {
        return "03".equals(transactionTypeCd);
    }

    /**
     * Checks if the transaction is a fee (type 04)
     * 
     * @return true if transaction type is '04' (Fee)
     */
    public boolean isFee() {
        return "04".equals(transactionTypeCd);
    }

    /**
     * Checks if the transaction is interest (type 05)
     * 
     * @return true if transaction type is '05' (Interest)
     */
    public boolean isInterest() {
        return "05".equals(transactionTypeCd);
    }

    /**
     * Checks if the transaction is internal (merchant ID 000000000)
     * 
     * @return true if merchant ID indicates internal transaction
     */
    public boolean isInternalTransaction() {
        return "000000000".equals(merchantId);
    }

    /**
     * Gets absolute value of transaction amount
     * 
     * @return absolute transaction amount
     */
    public BigDecimal getAbsoluteAmount() {
        return transactionAmount != null ? transactionAmount.abs() : BigDecimal.ZERO;
    }

    /**
     * Formats transaction amount for display
     * 
     * @return formatted amount string with currency symbol
     */
    public String getFormattedAmount() {
        if (transactionAmount == null) {
            return "$0.00";
        }
        return String.format("$%,.2f", transactionAmount);
    }

    /**
     * Gets transaction type description for display
     * 
     * Business rule: Maps transaction type codes to descriptions
     * 
     * @return transaction type description
     */
    public String getTransactionTypeDescription() {
        if (transactionTypeCd == null) {
            return "Unknown";
        }
        switch (transactionTypeCd) {
            case "01": return "Purchase";
            case "02": return "Cash Advance";
            case "03": return "Payment";
            case "04": return "Fee";
            case "05": return "Interest";
            default: return "Other";
        }
    }

    /**
     * Gets full merchant location for display
     * 
     * @return formatted merchant location (City, ZIP)
     */
    public String getMerchantLocation() {
        if (merchantCity == null && merchantZip == null) {
            return "";
        }
        if (merchantCity == null) {
            return merchantZip;
        }
        if (merchantZip == null) {
            return merchantCity;
        }
        return merchantCity + ", " + merchantZip;
    }

    // Object lifecycle methods

    /**
     * Validates business rules before persistence
     * 
     * Called automatically by JPA before INSERT/UPDATE operations
     */
    @PrePersist
    @PreUpdate
    private void validateBusinessRules() {
        // Ensure transaction amount precision matches COBOL S9(09)V99
        if (transactionAmount != null) {
            // Round to 2 decimal places to match COBOL precision
            transactionAmount = transactionAmount.setScale(2, BigDecimal.ROUND_HALF_UP);
        }
        
        // Set processing timestamp if not already set
        if (transactionProcTs == null) {
            transactionProcTs = LocalDateTime.now();
        }
        
        // Set original timestamp if not already set
        if (transactionOrigTs == null) {
            transactionOrigTs = LocalDateTime.now();
        }
        
        // Validate internal transaction rules
        if (isInternalTransaction() && (isPurchase() || isCashAdvance())) {
            throw new IllegalArgumentException("Internal transactions cannot be purchases or cash advances");
        }
        
        // Validate payment amount rules
        if (isPayment() && isDebit()) {
            throw new IllegalArgumentException("Payment transactions must have negative amounts (credits)");
        }
        
        // Validate fee and interest amount rules
        if ((isFee() || isInterest()) && isCredit()) {
            throw new IllegalArgumentException("Fee and interest transactions must have positive amounts (debits)");
        }
    }

    // Standard Object methods

    /**
     * Equality based on transaction ID (primary key)
     * 
     * @param obj object to compare
     * @return true if objects are equal
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null || getClass() != obj.getClass()) return false;
        Transaction transaction = (Transaction) obj;
        return Objects.equals(transactionId, transaction.transactionId);
    }

    /**
     * Hash code based on transaction ID
     * 
     * @return hash code value
     */
    @Override
    public int hashCode() {
        return Objects.hash(transactionId);
    }

    /**
     * String representation of Transaction entity
     * 
     * Note: Does not include sensitive card number for security
     * 
     * @return string representation
     */
    @Override
    public String toString() {
        return "Transaction{" +
                "transactionId='" + transactionId + '\'' +
                ", transactionTypeCd='" + transactionTypeCd + '\'' +
                ", transactionCategoryCd='" + transactionCategoryCd + '\'' +
                ", transactionSource='" + transactionSource + '\'' +
                ", transactionDesc='" + transactionDesc + '\'' +
                ", transactionAmount=" + transactionAmount +
                ", merchantId='" + merchantId + '\'' +
                ", merchantName='" + merchantName + '\'' +
                ", merchantCity='" + merchantCity + '\'' +
                ", merchantZip='" + merchantZip + '\'' +
                ", cardNumber='" + (cardNumber != null ? cardNumber.substring(0, 4) + "********" + cardNumber.substring(12) : null) + '\'' +
                ", accountId='" + accountId + '\'' +
                ", transactionOrigTs=" + transactionOrigTs +
                ", transactionProcTs=" + transactionProcTs +
                ", rowVersion=" + rowVersion +
                '}';
    }
}